### ISSUE TITLE
KeyError: 'page_count'

### ISSUE THREAD

**Issue by iampnp** [ricardorodrigues-ca/zoom-recording-downloader#16]
Getting user accounts...
Traceback (most recent call last):
  File "zoom-recording-downloader.py", line 284, in <module>
    main()
  File "zoom-recording-downloader.py", line 233, in main
    users = get_user_ids()
  File "zoom-recording-downloader.py", line 81, in get_user_ids
    total_pages = int(page_data['page_count']) + 1
KeyError: 'page_count'

**Comment by iampnp** [comment]
the issue was my JWT token.. thank you so much for this script. I'm testing it.. take care
