### ISSUE TITLE
example of appenv.py for a non developer user please

### ISSUE THREAD

**Issue by SSarrazola** [ricardorodrigues-ca/zoom-recording-downloader#20]
I managed to get everything running but I get an error 

Traceback (most recent call last):
  File "D:\Downloads\zoom-recording-downloader-master\zoom-recording-downloader-master\zoom-recording-downloader.py", line 17, in <module>
    from appenv import JWT_TOKEN
  File "D:\Downloads\zoom-recording-downloader-master\zoom-recording-downloader-master\appenv.py", line 1, in <module>
    JWT_TOKEN =eyJhbGciOiJIUzI1N*******************************2QnhrUXhPRzJrUWZHRi1rTEEiLCJleHAiOjE2NTE2MzM3NzMsImlhdCI6MTY1MT*********************************1HqBsisDjFTvVTRFDVf2O0
NameError: name 'eyJhbGciOiJIUzI1NiJ9' is not defined

I need an example of the appenv.py so I can start downloading

**Comment by ricardorodrigues-ca** [comment]
Put the token in quotes, like this:
`JWT_TOKEN='eyJhbGciOiJIUzI1NiJ9.E5SVnF2LXluOFEiLCJleHAiOjE2NDk0**g3MjcwNH0.pEAsJml371166Qi0hySOdK'`
