### ISSUE TITLE
Import of dependencies not working 

### ISSUE THREAD

**Issue by izzyyf** [ricardorodrigues-ca/zoom-recording-downloader#28]
I'm fairly new to coding... 
So I'm editing the script with VSCode on Ubuntu 22.04 and VSCode is giving me  the Warning: Import "tqdm" could not be resolved from sourcePylance[reportMissingModuleSource](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource)

If i try and run the script anyways I get this timeout error as shown below. I've run this script on another Ubuntu VM VirtualBox where it was successful but i mistakenly deleted the VM. I dont know whats different from last time, but i cant get it to run properly on Windows or Ubuntu now.

I have Python3.11 installed as well as pip. Any help would be greatly appreciated.
`                            

                           Zoom Recording Downloader

                                  Version 2.1

Log file not found. Creating new log file:  completed-downloads.log

Getting user accounts...

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn

    conn = connection.create_connection(

  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection

    raise err

  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection

    sock.connect(sa)

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen

    httplib_response = self._make_request(

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request

    self._validate_conn(conn)

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn

    conn.connect()

  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect

    conn = self._new_conn()

  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn

    raise ConnectTimeoutError(

urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen

    retries = retries.increment(

  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 288, in <module>

    main()

  File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 237, in main

    users = get_user_ids()

  File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 78, in get_user_ids

    response = requests.get(url=API_ENDPOINT_USER_LIST,

  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get

    return request('get', url, params=params, **kwargs)

  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send

    raise ConnectTimeout(e, request=request)

requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)'))`

**Comment by ricardorodrigues-ca** [comment]
Try installing it manually using one of the recommended methods listed here: https://pypi.org/project/tqdm/#installationOn Jan 16, 2023, at 7:40 PM, izzyyf ***@***.***> wrote:﻿
I'm fairly new to coding...
So I'm editing the script with VSCode on Ubuntu 22.04 and VSCode is giving me  the Warning: Import "tqdm" could not be resolved from sourcePylancereportMissingModuleSource
If i try and run the script anyways I get this timeout error as shown below. I've run this script on another Ubuntu VM VirtualBox where it was successful but i mistakenly deleted the VM. I dont know whats different from last time, but i cant get it to run properly on Windows or Ubuntu now.
I have Python3.11 installed as well as pip. Any help would be greatly appreciated.
`
                       Zoom Recording Downloader



                              Version 2.1

Log file not found. Creating new log file:  completed-downloads.log
Getting user accounts...
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
conn = connection.create_connection(

File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
raise err

File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
sock.connect(sa)

TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(

File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)

File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
conn.connect()

File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
conn = self._new_conn()

File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
raise ConnectTimeoutError(

urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(

File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(

File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 288, in 
main()

File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 237, in main
users = get_user_ids()

File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 78, in get_user_ids
response = requests.get(url=API_ENDPOINT_USER_LIST,

File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)

File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)

File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)

File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)

File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
raise ConnectTimeout(e, request=request)

requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)'))`

**Comment by izzyyf** [comment]
> Try installing it manually using one of the recommended methods listed here: https://pypi.org/project/tqdm/#installationOn Jan 16, 2023, at 7:40 PM, izzyyf ***@***.***> wrote:﻿ I'm fairly new to coding... So I'm editing the script with VSCode on Ubuntu 22.04 and VSCode is giving me the Warning: Import "tqdm" could not be resolved from sourcePylancereportMissingModuleSource If i try and run the script anyways I get this timeout error as shown below. I've run this script on another Ubuntu VM VirtualBox where it was successful but i mistakenly deleted the VM. I dont know whats different from last time, but i cant get it to run properly on Windows or Ubuntu now. I have Python3.11 installed as well as pip. Any help would be greatly appreciated. ` Zoom Recording Downloader Version 2.1 Log file not found. Creating new log file: completed-downloads.log Getting user accounts... Traceback (most recent call last): File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn conn = connection.create_connection( File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection raise err File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection sock.connect(sa) TimeoutError: [Errno 110] Connection timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request self._validate_conn(conn) File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn conn.connect() File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect conn = self._new_conn() File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn raise ConnectTimeoutError( urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send resp = conn.urlopen( File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen retries = retries.increment( File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 288, in main() File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 237, in main users = get_user_ids() File "/home/izzy/zoom-recording-downloader/zoom-recording-downloader.py", line 78, in get_user_ids response = requests.get(url=API_ENDPOINT_USER_LIST, File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get return request('get', url, params=params, **kwargs) File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send raise ConnectTimeout(e, request=request) requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.zoom.us', port=443): Max retries exceeded with url: /v2/users (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb9afba560>, 'Connection to api.zoom.us timed out. (connect timeout=None)'))` —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you very much
