### ISSUE TITLE
Download Error (KeyError)

### ISSUE THREAD

**Issue by svedriall** [ricardorodrigues-ca/zoom-recording-downloader#3]
```Getting recording list for User Name(x@x.com)
Traceback (most recent call last):
  File "/Users/pc/Desktop/zoom-recording-downloader-master/zoom-recording-downloader.py", line 270, in <module>
    main()
  File "/Users/pc/Desktop/zoom-recording-downloader-master/zoom-recording-downloader.py", line 230, in main
    recordings = list_recordings(user_id)
  File "/Users/pc/Desktop/zoom-recording-downloader-master/zoom-recording-downloader.py", line 141, in list_recordings
    recordings.extend(recordings_data['meetings'])
KeyError: 'meetings'
```

The first person's downloads are ok and perfectly downloaded but second user is not getting downloaded at all.

**Comment by origintopleft** [comment]
```
Traceback (most recent call last):
  File "/home/nicole/zoom-recording-downloader/zoom-recording-downloader.py", line 400, in <module>
    main()
  File "/home/nicole/zoom-recording-downloader/zoom-recording-downloader.py", line 331, in main
    recordings = list_recordings(user_id)
  File "/home/nicole/zoom-recording-downloader/zoom-recording-downloader.py", line 226, in list_recordings
    recordings.extend(recordings_data["meetings"])
KeyError: 'meetings'
```

(If the developer would prefer a new issue for this, I can do that)

The good news is I made it through a very large batch of users before encountering this.

**Comment by origintopleft** [comment]
Upon further investigation, it seems we hit API limits and the script did not handle that scenario gracefully. I've implemented an exponential backoff into a fork for now; once I get a chance to give it some polish I'll send it back up as a PR.

**Comment by sadokx** [comment]
Had this issue as well. Just one user, but 100 recordings. @ricardorodrigues-ca
