### ISSUE TITLE
Download fails when recording name begins with two spaces

### ISSUE THREAD

**Issue by mingomongo** [ricardorodrigues-ca/zoom-recording-downloader#36]
App is working great, but looks like it fails when a recording name begins with two spaces. One space doesn't seem to be a problem.

`==> Downloading (42 of 42) as shared_screen_with_speaker_view: c31ad18d-68d0-4086-9309-b51dba6b1a5c: https://us06web.zoom.us/rec/download/vLY_HzKRNgkd6HsoDFTz0LsLyxk...
Traceback (most recent call last):
  File "C:\Users\Danceworks Studio 10\Documents\zoom-recording-downloader-master\zoom-recording-downloader.py", line 288, in <module>
    main()
  File "C:\Users\Danceworks Studio 10\Documents\zoom-recording-downloader-master\zoom-recording-downloader.py", line 264, in main
    success |= download_recording(download_url, email, filename, foldername)
  File "C:\Users\Danceworks Studio 10\Documents\zoom-recording-downloader-master\zoom-recording-downloader.py", line 162, in download_recording
    os.makedirs(dl_dir, exist_ok=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 87] The parameter is incorrect: 'G:\\Shared drives\\Zen Box\\Zoom Recording Archives\\Downloads\\ ONLINE - Russian Ballet - Dmitri Gruzdev - GEN - £7 w& Dmitri Gruzdev - 2023.02.16 - 09.56 AM UTC'`

**Comment by mingomongo** [comment]
My bad, I think it's just a single space at the beginning
