### ISSUE TITLE
Server-to-Server OAuth not working as expected :(

### ISSUE THREAD

**Issue by iampnp** [ricardorodrigues-ca/zoom-recording-downloader#41]
Traceback (most recent call last):
  File "/root/zoom-recording-downloader/zoom-recording-downloader.py", line 325, in <module>
    main()
  File "/root/zoom-recording-downloader/zoom-recording-downloader.py", line 292, in main
    downloads = get_downloads(recording)
  File "/root/zoom-recording-downloader/zoom-recording-downloader.py", line 157, in get_downloads
    download_url = download['download_url'] + "?access_token=" + JWT_TOKEN
NameError: name 'JWT_TOKEN' is not defined

**Comment by ricardorodrigues-ca** [comment]
Working on a fix right now

**Comment by ricardorodrigues-ca** [comment]
Fix added to master branch.

**Comment by iampnp** [comment]
I have just now verified!
the new git clone of the repo and the new instruction of using zoom-recording-downloader.conf seems to be great and working great. it's downloading now. Please mark this issue as resloved.
