### ISSUE TITLE
KeyError: 'meetings'

### ISSUE THREAD

**Issue by pramoghub** [ricardorodrigues-ca/zoom-recording-downloader#51]
Hi
I am getting below meesage while running the code, have added all the scopes.
  File "E:\Scripts\zoom\zoom-recording-downloader.py", line 226, in list_recordings
    recordings.extend(recordings_data["meetings"])
                      ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: *meetings*
![zoom-error](https://github.com/ricardorodrigues-ca/zoom-recording-downloader/assets/169137658/0ea75ead-5b45-406d-8a40-428619433b97)

Kindly advise.

**Comment by mallorybowes** [comment]
I'm getting the same error and I'm doing my best to track it down.  I'm thinking it has to be a scope issue but adding all the scopes for the "Recording" area hasn't resolved it.  I'll post back if I figure it out..

**Comment by space215** [comment]
Bump , im getting the same issue , allowed  all scopes   however  wont work .

**Comment by jininvt** [comment]
Hey, did anyone manage to find the fix for this?

**Comment by savvasconstantinides** [comment]
This is a scope issue. Add the required scopes and it will work.

**Comment by ylanmuller** [comment]
I'm running into this as well, but the issue is it only happens partway through successful runs. The first time it uploaded 169 recordings before failing, and the next time it processed over 200 before failing with:

Getting recording list for [name] - [email]:
Traceback (most recent call last):
  File "/Users/username/github/security-corpit/zoom-recording-downloader/zoom-recording-downloader.py", line 461, in <module>
    main()
    ~~~~^^
  File "/Users/username/github/security-corpit/zoom-recording-downloader/zoom-recording-downloader.py", line 393, in main
    recordings = list_recordings(user_id)
  File "/Users/username/github/security-corpit/zoom-recording-downloader/zoom-recording-downloader.py", line 275, in list_recordings
    recordings.extend(recordings_data["meetings"])
KeyError: 'meetings'

I have all of the necessary scopes enabled and can't figure out why it would fail on a single user's recordings during one run, succeed the next, and then fail on another one later. Any ideas?

**Comment by ricardorodrigues-ca** [comment]
Added a check to ensure meetings exists in `recordings_data` before trying to access it. Please fetch the latest version of zoom-recording-downloader/zoom-recording-downloader.py and give it a try.

**Comment by ylanmuller** [comment]
Thanks for the quick attention on this, @ricardorodrigues-ca. I reran the program with the new version and it now properly returns 

"No 'meetings' key found in response for userId from 2024-08-28 00:00:00+00:00 to 2024-09-27 00:00:00+00:00" messages, but I am noticing as the names fly by that after it hit a certain person in the list (the same person it failed on last time), everyone after that returned no recordings, including a sampling of people where if I search the Zoom admin interface, I can see that they have recent recordings from that time period. What would cause that?

**Comment by ricardorodrigues-ca** [comment]
@ylanmuller Could you try a quick test of the API response for that specific problematic user? You can use this curl command (replace the placeholders):
`curl -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
"https://api.zoom.us/v2/users/PROBLEM_USER_ID/recordings?page_size=300&from=2024-01-01&to=2024-02-13"`

**Comment by ylanmuller** [comment]
Sure. I modified the query for a use that I can see has recordings in the admin console and two records were returned. I can't share the payload, but here is what it shows for the number of recordings brought back:

{"from":"2025-01-25","to":"2025-02-13","page_count":1,"page_size":300,"total_records":2,"next_page_token":"","meetings":[{}]}

And just a note that there is more than one problematic user in this case.

**Comment by ricardorodrigues-ca** [comment]
Here's a custom version of the script. 

I've added logging to capture the full API response for debugging (in the 'logs' subdirectory). Please review the API responses in the error logs for more detailed insights.

[zoom-recording-downloader.py.zip](https://github.com/user-attachments/files/18792747/zoom-recording-downloader.py.zip)

**Comment by ylanmuller** [comment]
Checking back in after 5 hours of running this to say that it is still going strong and I haven't encountered any errors yet. Will let you know if I hit any snags.

**Comment by ricardorodrigues-ca** [comment]
@ylanmuller The script was recently modified to handle OAuth token refresh if authentication expires.

**Comment by ylanmuller** [comment]
Can confirm it works perfectly now. Thank you!
