### ISSUE TITLE
Getting Error 'last_name'

### ISSUE THREAD

**Issue by DEPABUN** [ricardorodrigues-ca/zoom-recording-downloader#54]
Hi, can anyone help me solve this issue?
```
Log file not found. Creating new log file: completed-downloads.log

Getting user accounts...
Traceback (most recent call last):
  File "D:\zoom-recording-downloader\zoom-recording-downloader.py", line 400, in <module>
    main()
  File "D:\zoom-recording-downloader\zoom-recording-downloader.py", line 323, in main
    users = get_users()
            ^^^^^^^^^^^
  File "D:\zoom-recording-downloader\zoom-recording-downloader.py", line 134, in get_users
    user["last_name"]
    ~~~~^^^^^^^^^^^^^
KeyError: 'last_name'
```

**Comment by ricardorodrigues-ca** [comment]
Do you have any Zoom user accounts with blank last name fields? Anyway, try the updated 3.1 version and see if that works.

**Comment by ricardorodrigues-ca** [comment]
Just updated the script to handle this. It'll provide a default value for `last_name` if it is missing from the JSON data.

**Comment by DEPABUN** [comment]
> Just updated the script to handle this. It'll provide a default value for `last_name` if it is missing from the JSON data.

Hi @ricardorodrigues-ca , I just got new error. Can you help to resolve it?

`Getting recording list for [redacted - akun name] - xxx@gmail.com
Traceback (most recent call last):
  File "D:\zoom-recording-downloader-v3\zoom-recording-downloader-master\zoom-recording-downloader.py", line 462, in <module>
    main()
  File "D:\zoom-recording-downloader-v3\zoom-recording-downloader-master\zoom-recording-downloader.py", line 394, in main
    recordings = list_recordings(user_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\zoom-recording-downloader-v3\zoom-recording-downloader-master\zoom-recording-downloader.py", line 275, in list_recordings
    recordings.extend(recordings_data["meetings"])
                      ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'meetings'`

**Comment by ricardorodrigues-ca** [comment]
@DEPABUN Here's a custom version of the script. 

I've added logging to capture the full API response for debugging (in the 'logs' subdirectory). Please review the API responses in the error logs for more detailed insights.

[zoom-recording-downloader.py.zip](https://github.com/user-attachments/files/18792747/zoom-recording-downloader.py.zip)
